apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-daemonset
  namespace: devops-demo

spec:
  selector:
    matchLabels:
      app: demo-daemonset

  template:
    metadata:
      labels:
        app: demo-daemonset

    spec:
      containers:
        - name: demo-daemonset
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - while true; do echo "DaemonSet running on $(hostname)"; sleep 30; done
