apiVersion: v1
kind: Service
metadata:
  name: demo-statefulset
  namespace: devops-demo

spec:
  clusterIP: None

  selector:
    app: demo-statefulset

  ports:
    - name: http
      port: 80
      targetPort: 80
