apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
  namespace: devops-demo

spec:
  nodeName: k8s-worker-01

  containers:
    - name: busybox
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - sleep 3600

      volumeMounts:
        - name: demo-storage
          mountPath: /data

  volumes:
    - name: demo-storage
      persistentVolumeClaim:
        claimName: demo-pvc
